## Modified code for analyzing FitBit data
## Author: V

## Loading and preprocessing the data
# Downloading and unzipping data
if(!file.exists("datafile.zip")) {
    temp <- tempfile() # Temporary file to store downloaded data
    download.file("http://dataurl.com/datafile.zip", temp) # Downloading the data
    unzip(temp) # Unzipping the downloaded file
    unlink(temp) # Deleting the temporary file
}

data <- read.csv("activity.csv") # Reading the CSV file into 'data'

## Analysis
# Calculate total steps per day, create a histogram, and find mean and median
steps_by_day <- aggregate(steps ~ date, data, sum) # Aggregate steps by date
hist(steps_by_day$steps, main = "Steps Each Day", col = "blue", xlab = "Steps") # Creating a histogram of steps per day

rmean <- mean(steps_by_day$steps) # Calculating mean of steps
rmedian <- median(steps_by_day$steps) # Calculating median of steps

# Calculate average steps per interval for all days, plot the average steps per day by interval, and find the interval with the highest average steps
steps_by_interval <- aggregate(steps ~ interval, data, mean) # Aggregate steps by interval
plot(steps_by_interval$interval, steps_by_interval$steps, type = "l", xlab = "Interval", ylab = "Steps per Interval", main = "Average Steps per Day by Interval") # Creating a line plot of average steps per interval

max_interval <- steps_by_interval[which.max(steps_by_interval$steps), 1] # Finding the interval with the maximum average steps

# Impute missing values
incomplete <- sum(!complete.cases(data)) # Counting incomplete cases
imputed_data <- transform(data, steps = ifelse(is.na(data$steps), steps_by_interval$steps[match(data$interval, steps_by_interval$interval)], data$steps)) # Imputing missing values with the average steps for each interval

# Impute zeros for the first day
imputed_data[as.character(imputed_data$date) == "2012-01-01", 1] <- 0 # Imputing zeros for the first day

# Recalculate total steps per day and create a histogram
steps_by_day_i <- aggregate(steps ~ date, imputed_data, sum) # Aggregate steps by date for imputed data
hist(steps_by_day_i$steps, main = "Steps Each Day", col = "blue", xlab = "Steps") # Creating a histogram of steps per day for imputed data

# Calculate new mean and median for imputed data
rmean.i <- mean(steps_by_day_i$steps) # Calculating mean of steps for imputed data
rmedian.i <- median(steps_by_day_i$steps) # Calculating median of steps for imputed data

# Calculate differences
mean_diff <- rmean.i - rmean # Calculating difference in mean
med_diff <- rmedian.i - rmedian # Calculating difference in median
total_diff <- sum(steps_by_day_i$steps) - sum(steps_by_day$steps) # Calculating difference in total steps

# Compare activity patterns between weekdays and weekends
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday") # Defining weekdays
imputed_data$dow = as.factor(ifelse(is.element(weekdays(as.Date(imputed_data$date)), weekdays), "Weekday", "Weekend")) # Creating a factor variable for weekdays and weekends

steps_by_interval_i <- aggregate(steps ~ interval + dow, imputed_data, mean) # Aggregate steps by interval and day of the week

library(lattice)

xyplot(steps_by_interval_i$steps ~ steps_by_interval_i$interval|steps_by_interval_i$dow, main = "Average Steps per Day by Interval", xlab = "Interval", ylab = "Steps", layout = c(1,2), type = "l") # Creating a plot to compare steps per interval on weekdays and weekends
